
   - name: Install Elastic Search, Kibana, and Logstash (CentOS)
     yum:
       name:
         - elasticsearch
         - kibana
         - logstash

   - name: Start and Enable the Elastic Stack services (CentOS)
     systemd:
       name: "{{ item }}"
       state: restarted
       enabled: true
     loop:
       - elasticsearch
       - kibana
       - logstash



